server:
  port: 8002
  
spring:
  application:
    name: booking-service
    
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bookingdb
      
management:
  endpoints:
    web:
      exposure:
        include:
        - hystrix.stream
        
logging:
  level:
    '[com.user.service.BookingServiceImpl]' : info       
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

  file:
    path: logs                 